spring.application.name=api-usuarios
server.port=9000

spring.datasourcce.url=jdbc:sqlite:usuarios.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.show-sql=true
